name = "Hardcore Pack"
author = "Markflynnman"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "076f412c1517cb726d7ccf7829487750edcbc0734603aaca8b3e89525fef47db"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
