name = "Hardcore Pack"
author = "Markflynnman"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0e8caef129612de8d378957975637a8be1ae29e28deac52a046982ce45d078d"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
