name = "Hardcore Pack"
author = "Markflynnman"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc0e2c39649241e1a63c59ea962f5a203835dce36116ed33e216b0f81768a325"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
