name = "Hardcore Pack"
author = "Markflynnman"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2ac0096dc8e6334b00e5813b7613030a2da9873a406e8ad442461ff4ad9a7c4"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
