name = "Hardcore Pack"
author = "Markflynnman"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9da27caa7c71d3b85c3cc00e91245e705b646b7da1d2eae300975096d3a074a"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
